
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Common`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=localhost\SQLEXPRESS;Database=common;Integrated Security=True;`
//     Include Views:          `True`

namespace Gyomu.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the gyomu_apps_info_cdtbl table.
    /// </summary>
	[Table("gyomu_apps_info_cdtbl")]
	public partial class ApplicationInfo
	{
		[Key]
	    public virtual short application_id { get; set; }
	    public virtual string description { get; set; }
	    public virtual string mail_from_address { get; set; }
	    public virtual string mail_from_name { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_status_handler table.
    /// </summary>
	[Table("gyomu_status_handler")]
	public partial class StatusHandler
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual short application_id { get; set; }
	    public virtual string region { get; set; }
	    public virtual short? status_type { get; set; }
	    public virtual string recipient_address { get; set; }
	    public virtual string recipient_type { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_status_info table.
    /// </summary>
	[Table("gyomu_status_info")]
	public partial class StatusInfo
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual short application_id { get; set; }
		[Key]
	    public virtual DateTime entry_date { get; set; }
	    public virtual string entry_author { get; set; }
	    public virtual short status_type { get; set; }
	    public virtual short error_id { get; set; }
	    public virtual int instance_id { get; set; }
	    public virtual string hostname { get; set; }
	    public virtual string summary { get; set; }
	    public virtual string description { get; set; }
	    public virtual string developer_info { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_market_holiday table.
    /// </summary>
	[Table("gyomu_market_holiday")]
	public partial class MarketHoliday
	{
		[Key]
	    public virtual string market { get; set; }
	    public virtual short year { get; set; }
		[Key]
	    public virtual string holiday { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_milestone_daily table.
    /// </summary>
	[Table("gyomu_milestone_daily")]
	public partial class MilestoneDaily
	{
		[Key]
	    public virtual string target_date { get; set; }
		[Key]
	    public virtual string milestone_id { get; set; }
	    public virtual DateTime update_time { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_variable_parameter table.
    /// </summary>
	[Table("gyomu_variable_parameter")]
	public partial class VariableParameter
	{
		[Key]
	    public virtual string variable_key { get; set; }
	    public virtual string description { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_param_master table.
    /// </summary>
	[Table("gyomu_param_master")]
	public partial class ParameterMaster
	{
		[Key]
	    public virtual string item_key { get; set; }
	    public virtual string item_value { get; set; }
		[Key]
	    public virtual string item_fromdate { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_info_cdtbl table.
    /// </summary>
	[Table("gyomu_task_info_cdtbl")]
	public partial class TaskInfo
	{
		[Key]
	    public virtual short application_id { get; set; }
		[Key]
	    public virtual short task_id { get; set; }
	    public virtual string description { get; set; }
	    public virtual string assembly_name { get; set; }
	    public virtual string class_name { get; set; }
	    public virtual bool restartable { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_info_access_list table.
    /// </summary>
	[Table("gyomu_task_info_access_list")]
	public partial class TaskAccessList
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
		[Key]
	    public virtual short application_id { get; set; }
		[Key]
	    public virtual short task_info_id { get; set; }
		[Key]
	    public virtual string account_name { get; set; }
	    public virtual bool can_access { get; set; }
	    public virtual bool forbidden { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_data table.
    /// </summary>
	[Table("gyomu_task_data")]
	public partial class TaskData
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual short application_id { get; set; }
	    public virtual short task_info_id { get; set; }
		[Key]
	    public virtual DateTime entry_date { get; set; }
	    public virtual string entry_author { get; set; }
	    public virtual long? parent_task_data_id { get; set; }
	    public virtual string parameter { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_instance table.
    /// </summary>
	[Table("gyomu_task_instance")]
	public partial class TaskInstance
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long task_data_id { get; set; }
		[Key]
	    public virtual DateTime entry_date { get; set; }
	    public virtual string entry_author { get; set; }
	    public virtual string task_status { get; set; }
	    public virtual bool is_done { get; set; }
	    public virtual long? status_info_id { get; set; }
	    public virtual string parameter { get; set; }
	    public virtual string comment { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_instance_submit_information table.
    /// </summary>
	[Table("gyomu_task_instance_submit_information")]
	public partial class TaskSubmitInformation
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
		[Key]
	    public virtual long task_instance_id { get; set; }
		[Key]
	    public virtual string submit_to { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_data_status table.
    /// </summary>
	[Table("gyomu_task_data_status")]
	public partial class TaskDataStatus
	{
		[Key]
	    public virtual long task_data_id { get; set; }
	    public virtual string task_status { get; set; }
	    public virtual DateTime latest_update_date { get; set; }
	    public virtual long latest_task_instance_id { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_data_log table.
    /// </summary>
	[Table("gyomu_task_data_log")]
	public partial class TaskDataLog
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
		[Key]
	    public virtual long task_data_id { get; set; }
		[Key]
	    public virtual DateTime log_time { get; set; }
	    public virtual string log { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_service_type_cdtbl table.
    /// </summary>
	[Table("gyomu_service_type_cdtbl")]
	public partial class ServiceType
	{
		[Key]
	    public virtual short id { get; set; }
	    public virtual string description { get; set; }
	    public virtual string assembly_name { get; set; }
	    public virtual string class_name { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_service_cdtbl table.
    /// </summary>
	[Table("gyomu_service_cdtbl")]
	public partial class Service
	{
		[Key]
	    public virtual short id { get; set; }
	    public virtual string description { get; set; }
	    public virtual short service_type_id { get; set; }
	    public virtual string parameter { get; set; }
	}

    /// <summary>
    /// A class which represents the gyomu_task_scheduler_config table.
    /// </summary>
	[Table("gyomu_task_scheduler_config")]
	public partial class TaskSchedulerConfig
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual short service_id { get; set; }
	    public virtual string description { get; set; }
	    public virtual short application_id { get; set; }
	    public virtual short task_id { get; set; }
	    public virtual string monitor_parameter { get; set; }
	    public virtual DateTime next_trigger_time { get; set; }
	    public virtual string task_parameter { get; set; }
	    public virtual bool is_enabled { get; set; }
	}

}

