DROP TABLE if exists task_data_log;

DROP TABLE if exists task_data_status;


DROP TABLE if exists task_instance_submit_information;


DROP TABLE if exists task_instance;

DROP TABLE if exists task_data;


DROP TABLE if exists task_info_access_list;


DROP TABLE if exists task_info_cdtbl;

CREATE TABLE task_info_cdtbl(
	application_id smallint NOT NULL,
	task_id smallint NOT NULL,
	description varchar(100) NOT NULL,
	assembly_name varchar(100) NOT NULL,
	class_name varchar(100) NOT NULL,
	restartable boolean NOT NULL,
 PRIMARY KEY (application_id,	task_id )
);

CREATE TABLE task_info_access_list(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	application_id smallint NOT NULL,
	task_info_id smallint NOT NULL,
	account_name varchar(100) NOT NULL,
	can_access boolean NOT NULL,
	forbidden boolean NOT NULL
);

CREATE INDEX CX_task_info_access_list ON task_info_access_list
(
	application_id ASC, task_info_id ASC,account_name ASC
);

CLUSTER task_info_access_list USING CX_task_info_access_list;


CREATE TABLE task_data(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	application_id smallint NOT NULL,
	task_info_id smallint NOT NULL,
	entry_date timestamp with time zone NOT NULL default CURRENT_TIMESTAMP ,
	entry_author varchar(30) NOT NULL,
	parent_task_data_id bigint NULL,
	parameter text NULL
);


CREATE INDEX CX_task_data ON task_data
(
	entry_date ASC
);

CLUSTER task_data USING CX_task_data;

CREATE INDEX IX_task_data1 ON task_data
(
	application_id ASC
) ;

CREATE INDEX IX_task_data2 ON task_data
(
	task_info_id ASC
) ;

CREATE INDEX IX_task_data3 ON task_data
(
	entry_author ASC
) ;




CREATE TABLE task_instance(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	task_data_id bigint NOT NULL,
	entry_date timestamp with time zone NOT NULL default CURRENT_TIMESTAMP ,
	entry_author varchar(30) NOT NULL,
	task_status varchar(10) NULL,
	is_done boolean NOT NULL,
	status_info_id bigint NULL,
	parameter text NULL,
	comment text NULL
);


CREATE INDEX CX_task_instance ON task_instance
(
	entry_date ASC
);

CLUSTER task_instance USING CX_task_instance;


CREATE INDEX IX_task_instance1 ON task_instance
(
	task_data_id ASC
) ;

CREATE INDEX IX_task_instance2 ON task_instance
(
	task_status ASC
) ;



CREATE TABLE task_instance_submit_information(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	task_instance_id bigint NOT NULL,
	submit_to varchar(30) NULL
);

CREATE INDEX CX_task_instance_submit_information ON task_instance_submit_information
(
	task_instance_id ASC,
	submit_to ASC
);

CLUSTER task_instance_submit_information USING CX_task_instance_submit_information;


CREATE TABLE task_data_status(
	task_data_id bigint PRIMARY KEY,
	task_status varchar(10) NULL,
	latest_update_date timestamp with time zone NOT NULL,
	latest_task_instance_id bigint NOT NULL
);




CREATE TABLE task_data_log(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	task_data_id bigint NOT NULL,
	log_time timestamp with time zone NOT NULL default CURRENT_TIMESTAMP ,
	log text NOT NULL
) ;

CREATE INDEX CX_task_data_log ON task_data_log
(
	task_data_id ASC,	log_time ASC
);

CLUSTER task_data_log USING CX_task_data_log;
