
DROP TABLE if exists status_info;

DROP TABLE if exists status_handler;

DROP TABLE if exists apps_info_cdtbl;

DROP TABLE if exists status_type_cdtbl;

DROP TABLE if exists market_holiday;

DROP TABLE IF EXISTS milestone_daily;

DROP TABLE IF EXISTS variable_parameter;

CREATE TABLE apps_info_cdtbl(
	application_id smallint PRIMARY KEY ,
	description varchar(50) NULL,
	mail_from_address varchar(200) NULL,
	mail_from_name varchar(200) NULL
);

CREATE TABLE status_type_cdtbl(
	status_type SMALLINT PRIMARY KEY,
	description varchar(15) NULL
);

INSERT INTO status_type_cdtbl VALUES (0,'INFO');
INSERT INTO status_type_cdtbl VALUES (1,'WARNING');
INSERT INTO status_type_cdtbl VALUES (2,'ERROR_BUSINESS');
INSERT INTO status_type_cdtbl VALUES (8,'ERROR_DEVEL');

CREATE TABLE status_handler(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	application_id smallint NOT NULL,
	region varchar(3) NULL,
	status_type SMALLINT NULL,
	recipient_address varchar(200) NULL,
	recipient_type varchar(3) NULL
);

CREATE TABLE status_info(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	application_id smallint NOT NULL,
	entry_date timestamp with time zone NOT NULL default CURRENT_TIMESTAMP ,
	entry_author varchar(30) NOT NULL,
	status_type SMALLINT NULL,
	error_id smallint NOT NULL,
	instance_id int NULL,
	hostname varchar(50) NULL,
	summary varchar(400) NULL,
	description varchar(1000) NULL,
	developer_info text NULL
);


CREATE INDEX CX_status_info ON status_info
(
	entry_date ASC
);

CLUSTER status_info USING CX_status_info;


CREATE TABLE market_holiday(
	market varchar(10) NOT NULL,
	year smallint NOT NULL,
	holiday char(8) NOT NULL,
 PRIMARY KEY (market,	holiday )
);

CREATE INDEX IX_market_holiday ON market_holiday
(market ASC,year ASC);


CREATE TABLE milestone_daily(
	target_date varchar(8) NOT NULL,
	milestone_id varchar(200) NOT NULL,
  update_time timestamp with time zone NOT NULL default CURRENT_TIMESTAMP ,
 PRIMARY KEY (target_date,	milestone_id )
);

CREATE  INDEX IX_target_date ON milestone_daily
(
	milestone_id
);

CREATE TABLE variable_parameter(
	variable_key varchar(20) PRIMARY KEY ,
	description varchar(200) NOT NULL);

INSERT INTO VARIABLE_PARAMETER VALUES('BBOM','Business Day of Beginning Of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('BBOY','Business Day of Beginning Of Year');
INSERT INTO VARIABLE_PARAMETER VALUES('BOM','Beginning of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('BOY','Beginning of Year');
INSERT INTO VARIABLE_PARAMETER VALUES('BEOM','Business Day of End Of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('BEOY','Business Day of End Of Year');
INSERT INTO VARIABLE_PARAMETER VALUES('EOM','End of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('EOY','End Day of Year');
INSERT INTO VARIABLE_PARAMETER VALUES('NEXTBBOM','Business Day of Next Beginning Of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('NEXTBUS','Previous Business Day');
INSERT INTO VARIABLE_PARAMETER VALUES('NEXTDAY','Next Day');
INSERT INTO VARIABLE_PARAMETER VALUES('NEXTBEOM','Business Day of Next End Of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('PARAMMASTER','From param_master');
INSERT INTO VARIABLE_PARAMETER VALUES('PREVBUS','Previous Business Day');
INSERT INTO VARIABLE_PARAMETER VALUES('PREVDAY','Previous Day');
INSERT INTO VARIABLE_PARAMETER VALUES('PREVBEOM',' Business Day of Previous End Of Month');
INSERT INTO VARIABLE_PARAMETER VALUES('TODAY','Today');